.Dd $Mdocdate$
.Dt harp_length 3 "libharp manual"

.Sh NAME

.Nm harp_length
.Nd count elements of lists

.Sh SYNOPSIS
.In harp.h
.Ft int
.Fn harp_length "harp_list_t *list"

.Sh DESCRIPTION

The
.Fn harp_length
function walks through the list and counts the number of elements in
.Fa list .

.Sh SEE ALSO

.Xr harp_singleton 3 ,
.Xr harp_last 3
